services:
  omni-infra-provider-proxmox:
    image: ghcr.io/siderolabs/omni-infra-provider-proxmox
    container_name: omni-infra-provider-proxmox
    env_file:
      - .env
    volumes:
      - ./config.yaml:/config.yaml
    command: >
      --config-file /config.yaml
      --omni-api-endpoint ${OMNI_API_ENDPOINT}
      --omni-service-account-key ${OMNI_INFRA_PROVIDER_KEY}
    restart: unless-stopped
    network_mode: host